# Generated by Django 3.1 on 2020-09-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catogery',
            new_name='categery',
        ),
    ]
