# Generated by Django 3.1 on 2020-09-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200906_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(default='10'),
            preserve_default=False,
        ),
    ]
